#
# Copyright 2025 okdp.io
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

name: build, test and publish to ci registry

on:
  workflow_call:
    inputs:
      context:
        description: Docker context
        required: false
        type: string
        default: '.'
      dockerfile:
        description: Dockerfile path
        required: true
        type: string
      image:
        description: Image name
        required: false
        type: string
        default: 'superset'
      ci_registry:
        description: "The registry used to push ci images"
        required: false
        type: string
        default: "ghcr.io"
      add-tag-suffix:
        description: "Optional suffix to append to the Docker image tag (e.g. '-dockerize' or '-websocket'). Leave empty for no suffix."
        required: false
        type: string
        default: ""

defaults:
  run:
    shell: bash

jobs:

  docker-build-test-push:
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout Repo âš¡ï¸
        uses: actions/checkout@v4

#      - name: Free up disk space ğŸ“¦
#        uses: okdp/gh-workflows/.github/actions/free-disk-space@v1

      - name: Set up QEMU and Docker Buildx ğŸ“¦
        uses: okdp/gh-workflows/.github/actions/setup-buildx@v1

      - name: Set up container registry ğŸ“¦
        id: ci_registry
        run:  |
            echo "ci_registry=${{ vars.CI_REGISTRY || inputs.ci_registry }}" >> $GITHUB_OUTPUT
            echo "registry_repo=${{ vars.CI_REGISTRY || inputs.ci_registry }}/${GITHUB_REPOSITORY_OWNER@L}" >> $GITHUB_OUTPUT

      - name: Get Git Branch Name Action
        id: get-branch
        uses: okdp/gh-workflows/.github/actions/git-branch@v1
        with:
          event_name: ${{ github.event_name }}
          ref: ${{ github.ref }}
          head_ref: ${{ github.head_ref }}

      - name: Set CI image tag
        id: image-tag
        run: |
            echo "ci_tag=${{ steps.ci_registry.outputs.registry_repo }}/${{ inputs.image }}:${{ steps.get-branch.outputs.branch }}${{ inputs.add-tag-suffix }}" >> $GITHUB_OUTPUT
            echo "ci_tag=$ci_tag" >> $GITHUB_ENV
            echo "Set image tag to: $ci_tag"

      - name: Login into ${{ steps.ci_registry.outputs.ci_registry }} registry ğŸ”
        uses: docker/login-action@v3
        with:
          registry: ${{ steps.ci_registry.outputs.ci_registry }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push image ${{ steps.image-tag.outputs.ci_tag }} ğŸ“¤
        uses: docker/build-push-action@v5
        with:
          context: ${{ inputs.context }}
          file: ${{ inputs.dockerfile }}
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.image-tag.outputs.ci_tag }}


